Lint
chaoswest-tv/infra pull request #1
Opened 2020-04-21 18:18 UTC by DO1JLR

fixed all linting warnings and add meta for all roles

2020-04-23 14:45 UTC, DO1JLR commented
ping @JanKoppe 
Ich hab endlich bischen was hieran gemacht :wink:

2020-04-29 07:40 UTC, JanKoppe requested changes
Thank you very much! Lots of work done here :)

Overall it seems like you did not mention the focal Ubuntu release as a platform, which we are now using though. It's the super-new 20.04 LTS release.

And some nit-picking: "CHAOSWEST TV" seems weird. "Chaoswest TV" is a more friendly capitalization I think.

2020-04-29 07:40 UTC, JanKoppe commented on roles/docker/meta/main.yaml
> +  description: iAdd repo and install docker
typo in "iAdd"

2020-04-29 07:40 UTC, JanKoppe commented on roles/grafana/meta/main.yaml
> +  description: Install grafana and prometheus
This role does not install prometheus.

2020-04-29 07:40 UTC, JanKoppe commented on roles/srs_edge/meta/main.yaml
> +  description: compile edge server and open rtmp firewall port
should be "deploy SRS edge server".
- compilation is only done for the configuration file (from the template), not the actual SRS code.
- firewall ports are opened in other roles as well, but not mentioned in the description.

2020-04-29 07:40 UTC, JanKoppe commented on roles/srs_origin/meta/main.yaml
> +  description: compile origin server and open rtmp firewall port
should be "deploy SRS origin server".
* compilation is only done for the configuration file (from the template), not the actual SRS code.
* firewall ports are opened in other roles as well, but not mentioned in the description.

2020-04-29 07:48 UTC, DO1JLR commented on roles/srs_origin/meta/main.yaml
> +  description: compile origin server and open rtmp firewall port
Thanks, it is updated

2020-04-29 07:49 UTC, DO1JLR commented on roles/srs_edge/meta/main.yaml
> +  description: compile edge server and open rtmp firewall port
:heavy_check_mark: makes sense

2020-04-29 07:50 UTC, DO1JLR commented on roles/grafana/meta/main.yaml
> +  description: Install grafana and prometheus
updated to ``install grafana``

2020-04-29 07:50 UTC, DO1JLR commented on roles/docker/meta/main.yaml
> +  description: iAdd repo and install docker
:heavy_check_mark: typo, sorry

2020-04-29 12:16 UTC, DO1JLR commented
> Thank you very much! Lots of work done here :)
:heart: 

> Overall it seems like you did not mention the focal Ubuntu release as a platform, which we are now using though. It's the super-new 20.04 LTS release.

I didn't add this because the lint check at galaxy.ansible.com did not know this ubuntu version yet. But since this is not at galaxy and Ubuntu 20.4 is a LTS version again, there is no reason not to include it in the meta infos... so I just did that :wink:

> And some nit-picking: "CHAOSWEST TV" seems weird. "Chaoswest TV" is a more friendly capitalization I think.
good point. It is changed.

2020-04-29 17:33 UTC, JanKoppe approved these changes

2020-04-29 17:33 UTC, merged