Add MIT License
chaoswest-tv/infra pull request #2
Opened 2020-04-21 18:19 UTC by DO1JLR

Copyright (c) 2020 Jan Koppe <post@jankoppe.de>
Copyright (c) 2020 L3D <l3d@c3woc.de>
Copyright (c) 2020 CHAOSWEST TV <post@chaoswest.tv>

2020-04-29 17:34 UTC, JanKoppe requested changes

2020-04-29 17:34 UTC, JanKoppe commented on LICENSE
> +Copyright (c) 2020 CHAOSWEST TV <post@chaoswest.tv>
nit-picking, same as in #1 :) Would you be so kind to use Chaoswest TV capitalization? Thanks!

2020-04-30 07:43 UTC, DO1JLR commented on LICENSE
> +Copyright (c) 2020 CHAOSWEST TV <post@chaoswest.tv>
``s/CHAOSWEST TV/Chaoswest TV/g``

2020-05-01 22:15 UTC, JanKoppe approved these changes
LGTM

2020-05-01 22:15 UTC, merged