add github action lint-check
chaoswest-tv/infra pull request #3
Opened 2020-04-21 18:29 UTC by DO1JLR

Add [this](https://github.com/marketplace/actions/ansible-lint) github-action for Ansible Lint.

please first merge #1 because that will repair all ansible-lint warnings.

2020-04-29 17:35 UTC, JanKoppe requested changes

2020-04-29 17:35 UTC, JanKoppe commented on .github/workflows/ansible-lint.yml
> +name: Ansible Lin
typo-man has struck again! :scream:

2020-04-30 07:48 UTC, DO1JLR commented on .github/workflows/ansible-lint.yml
> +name: Ansible Lin
oh nooo, not again, how evil

2020-05-01 22:16 UTC, JanKoppe approved these changes
LGTM

2020-05-01 22:16 UTC, merged